# Generated by Django 6.0.6 on 2026-06-23 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('gamesdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('plataforma', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='plataforma.juego')),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
        migrations.CreateModel(
            name='BibliotecaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_items', to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_items', to='plataforma.juego')),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
    ]
