# Generated by Django 6.0.5 on 2026-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='steam_appid',
        ),
        migrations.AddField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='gamesdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
