# Generated by Django 6.0.5 on 2026-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_carritoitem_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
