# Generated by Django 6.0.5 on 2026-06-23 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_juego_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('usuario', 'juego')},
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='plataforma.juego'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='cantidad',
        ),
    ]
