# Generated by Django 6.0.5 on 2026-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_bibliotecaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen_local',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
